version: "3.2"
services:
  redis:
    image: redis
    volumes: 
      - ./data:/data
  users-commands:
    volumes:
        - ./usuarios/:/mnt/
    build: ./usuarios
    working_dir: /backend/
    command: sh run_commands.sh
    depends_on: 
      - redis
  nginx:
    image: nginx:latest
    ports:
      - 5002:8080
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - users-commands

